### ISSUE TITLE
Component returns None 

### ISSUE THREAD

**Issue by edsaac** [ShruAgarwal/streamlit-custom-toggle#1]
I expected the component to return `True` or `False` (like st.checkbox) but it returns `None`. Maybe it was an issue with the key but not passing one doesn't make a difference. 

![image|552x246, 50%](https://user-images.githubusercontent.com/34405119/203459466-f653db45-37eb-4f9f-bfdd-20d9471a88e4.png)

Some code to reproduce:  

```python
import streamlit as st
from streamlit_custom_toggle import st_custom_toggle

st.header('Music Choices 🎵')

col1, col2, col3 = st.columns(3, gap="small")
with col1:
    calm = st_custom_toggle(
        'Calm', 
        active_track_fill="#EAE4E4", 
        active_thumb_color="#EAE4E4", 
        value="true", 
        key="toggle1")  # Disabled toggle switch

with col2:
    fun = st_custom_toggle(
        'Fun', 
        active_track_fill="#57FD6E", 
        active_thumb_color="#EAE4E4", 
        key="toggle2")

with col3:
    rock = st_custom_toggle(
        'Rock', 
        active_track_fill="#FF5733", 
        active_thumb_color="#900C3F")

st.code(f"Calm = {calm}, Fun = {fun}, Rock = {rock}")
```

**Comment by ShruAgarwal** [comment]
Thanks, @edsaac for pointing that out! 🙂
To be honest, I realized this after publishing the package. Will definitely make that change 👍

**Comment by ShruAgarwal** [comment]
Hey, @edsaac 👋
I'm back with a new version to fix the issue. 🙂 
You can upgrade your installation using `pip install --upgrade streamlit-custom-toggle` to its latest version.

I've also built an app to showcase its working! Please read `README.md`
Hope it helps solve this issue. Please share your feedback! 😊
